// import useSettings from 'app/hooks/useSettings';

// const MatxLogo = ({ className }) => {
//   const { settings } = useSettings();
//   const theme = settings.themes[settings.activeTheme];

//   return (
//     <svg
//       width="24px"
//       height="24px"
//       className={className}
//       viewBox="0 0 240 239"
//       version="1.1"
//       xmlns="http://www.w3.org/2000/svg"
//       xmlnsXlink="http://www.w3.org/1999/xlink"
//     >
//       <g id="Page-1" stroke="none" strokeWidth="1" fill="none" fillRule="evenodd">
//         <g
//           id="logo"
//           transform="translate(120.500000, 98.000000) rotate(-270.000000) translate(-120.500000, -98.000000) translate(-21.000000, -35.000000)"
//         >
//           <g
//             id="Group"
//             transform="translate(141.500000, 133.000000) rotate(90.000000) translate(-141.500000, -133.000000) translate(9.000000, -8.000000)"
//           >
//             <g
//               id="Path-4-Copy"
//               transform="translate(132.242532, 149.243361) rotate(-135.000000) translate(-132.242532, -149.243361) translate(38.742532, 55.743361)"
//             >
//               <g id="path-1-link" fill="#000000">
//                 <polygon
//                   id="path-1"
//                   points="136.269985 0.8695976 186.615824 50.367072 186.615824 186.98041 50.7100649 186.98041 0.4346189 136.704964"
//                 ></polygon>
//               </g>
//               <g id="path-1-link" fill={theme.palette.primary.light}>
//                 <polygon
//                   id="path-1"
//                   points="136.269985 0.8695976 186.615824 50.367072 186.615824 186.98041 50.7100649 186.98041 0.4346189 136.704964"
//                 ></polygon>
//               </g>
//             </g>
//             <polygon
//               id="Path-3"
//               fill={theme.palette.primary.light}
//               points="13 238.415212 13 0 249.898437 238.415212"
//             ></polygon>
//             <polygon
//               id="Path-4"
//               fill={theme.palette.primary.main}
//               points="252.486992 0 252.486992 238.799226 13 238.799226"
//             ></polygon>
//           </g>
//         </g>
//       </g>
//     </svg>
//   );
// };

// export default MatxLogo;

/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preseve that abilty, always export from Quest to regenerate this file.
 *   To setup props, bindings and actions, use the Quest editor
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
// import VectorImage from '/assets/images/Logo_Vector.png';
// import Vector1Image from '/assets/images/Logo_Vector_1.png';
// import Vector2Image from '/assets/images/Logo_Vector_2.png';
// import Vector3Image from '/assets/images/Logo_Vector_3.png';
// import Vector4Image from '/assets/images/Logo_Vector_4.png';
// import Vector5Image from '/assets/images/Logo_Vector_5.png';
// import Vector6Image from '/assets/images/Logo_Vector_6.png';

import { styled } from '@mui/material/styles';

const Logo1 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  height: `40px`,
  width: '100%',
  justifyContent: `center`,
  alignItems: `center`,
  padding: `10px`,
  boxSizing: `border-box`,
  maxWidth: '128px',
  minWidth: '128px',
});

const Logo2 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  height: `24px`,
  width: `109.02px`,
  margin: `0px`,
  overflow: `hidden`,
});

const Vector = styled('img')({
  height: `13.87px`,
  width: `29.21px`,
  position: `absolute`,
  left: `51px`,
  top: `7px`,
});

const Vector1 = styled('img')({
  height: `14.19px`,
  width: `17.1px`,
  position: `absolute`,
  left: `92px`,
  top: `7px`,
});

const Vector2 = styled('img')({
  height: `13.17px`,
  width: `17.09px`,
  position: `absolute`,
  left: `11px`,
  top: `7px`,
});

const Vector3 = styled('img')({
  height: `13.19px`,
  width: `17.07px`,
  position: `absolute`,
  left: `31px`,
  top: `7px`,
});

const Vector4 = styled('img')({
  height: `19.38px`,
  width: `8.2px`,
  position: `absolute`,
  left: `0px`,
  top: `1px`,
});

const Vector5 = styled('img')({
  height: `13.7px`,
  width: `4.31px`,
  position: `absolute`,
  left: `84px`,
  top: `7px`,
});

const Vector6 = styled('img')({
  height: `5.33px`,
  width: `5.27px`,
  position: `absolute`,
  left: `84px`,
  top: `0px`,
});

function MatxLogo(props) {
  return (
    <Logo1 className={props.className}>
      <Logo2>
        <Vector src= {"/assets/images/Logo_Vector.png"} loading="lazy" alt={'Vector'} />
        <Vector1 src={"/assets/images/Logo_Vector_1.png"} loading="lazy" alt={'Vector'} />
        <Vector2 src={"/assets/images/Logo_Vector_2.png"} loading="lazy" alt={'Vector'} />
        <Vector3 src={"/assets/images/Logo_Vector_3.png"} loading="lazy" alt={'Vector'} />
        <Vector4 src={"/assets/images/Logo_Vector_4.png"} loading="lazy" alt={'Vector'} />
        <Vector5 src={"/assets/images/Logo_Vector_5.png"} loading="lazy" alt={'Vector'} />
        <Vector6 src={"/assets/images/Logo_Vector_6.png"} loading="lazy" alt={'Vector'} />
      </Logo2>
    </Logo1>
  );
}

export default MatxLogo;

